Update centos.md
I tried to install a specific error and the following error occurs:
Error: Unable to find a match: docker-ce-cli-3:24.0.2-1.el8
It happens because docker-ce-cli has a different version number.